services:
  - type: web
    name: kanban-board-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-board-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
